#!/bin/sh
# /usr/share/sddm/scripts/Xsetup - run as root before the login dialog appears

# Keyboards
#kb_script="/home/julio/bin/keyboards.sh"
#[ -s "$kb_script" ] && \. "$kb_script"


# Nvidia
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

# Force Composition Pipeline
nfcp_script="/home/julio/bin/nvidia-force_comp_pipeline.sh"
[ -s "$nfcp_script" ] && \. "$nfcp_script"
