#!/usr/bin/env python3
# -*-*- encoding: utf-8 -*-*-

"""
Document here.
"""


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
import os
import sys
import argparse
import logging


__author__ = "$USER_FULLNAME"
__copyright__ = "$USER_COPYRIGHT"
__license__ = "GPL v3"
__version__ = "1.0"
__email__ = "$USER_EMAIL"


SCRIPT_DIR = os.path.dirname(__file__)
SCRIPT_NAME = os.path.basename(__file__)


def main():
    '''Função principal'''

    return 0


if __name__ == "__main__":
    PARSER = argparse.ArgumentParser(
        description='Este programa...')
    PARSER.add_argument('-b', '--bar', dest="bar",
        help='bar help')
    PARSER.add_argument('-n', '--num', type=int,
        help="integer")
    PARSER.add_argument('-f', '--force', action='store_true',
        default=False, dest='force',
        help='force')
    PARSER.add_argument("-v", "--verbosity", action="count", default=0,
        help="increase output verbosity")
    PARSER.add_argument('--version', action='version',
        version='%(prog)s v' + __version__)
    ARGS = PARSER.parse_args()

    logging.basicConfig(
        filename=os.path.join(SCRIPT_DIR, SCRIPT_NAME + '.log'),
        format='%(asctime)s %(levelname)-8s %(message)s',
        level=logging.INFO,
        datefmt='%Y-%m-%d %H:%M:%S')

    logging.debug("===================Iniciou o script===================")

    try:
        sys.exit(main())
    except KeyboardInterrupt:
        logging.debug("=====================Interrompido=====================")
        sys.exit(0)
    except SystemExit:
        logging.debug("==================Finalizou o script==================")
    except BaseException:
        logging.exception('Ocorreu um erro')
