#!/usr/bin/env python2
# -*-*- encoding: utf-8 -*-*-

"""
Document here.
"""


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
import argparse
import sys


__author__ = "$USER_FULLNAME"
__copyright__ = "$USER_COPYRIGHT"
__license__ = "GPL v3"
__version__ = "1.0"
__email__ = "$USER_EMAIL"


def main(args):
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
            description='Descricao do programa.')
    parser.add_argument('-b', '--bar', dest="bar", help='bar help')
    parser.add_argument('-n', '--num', type=int, help="integer")
    parser.add_argument('-f', '--force', action='store_true',
            default=False, dest='force', help='force')
    parser.add_argument("-v", "--verbosity", action="count", default=0,
            help="increase output verbosity")
    parser.add_argument('--version', action='version',
            version='%(prog)s v' + __version__)
    args = parser.parse_args()

    sys.exit(main(args))
