tasks:
  ???-tv_xvid_sd:
    rss: http://example.com/rss?download;l79;l5;14;u=123;tp=012345
    series:
      - Breaking Bad:
          watched: S05E08
      - Boardwalk Empire:
          watched: S03E07
      - Doctor Who:
          watched: S07E02
      - Dexter:
          quality: 720p
          watched: S07E01
      - Touch:
          quality: 720p
          watched: S02E02
      - Game of Thrones:
          quality: 720p
          watched: S02E09
      - The Big Bang Theory:
          watched: S06E15
      - Revolution:
          watched: S01E10
      - The Walking Dead:
          watched: S03E08
      - Family Guy:
          watched: S11E01
      - Community:
          watched: S04E01
      - Always Sunny in Philadelphia:
          watched: S08E10
    download: /media/hd2/Torrents/rtorrent/watch/Seriados/

#Atualizado em 09/02/2013
